import { StyleSheet } from 'react-native';

import { Radius, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: Spacing.xl }, eyebrow: { fontSize: 12, fontWeight: '800', letterSpacing: 1.2 }, heading: { fontSize: 26, fontWeight: '700', marginTop: 4 }, iconButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, form: { paddingHorizontal: Spacing.xl, paddingBottom: 110, gap: Spacing.xl },
  searchWrap: { zIndex: 5 }, searchInputWrap: { minHeight: 56, borderWidth: 1.5, borderRadius: Radius.md, paddingHorizontal: Spacing.lg, flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, titleInput: { flex: 1, fontSize: 17, fontWeight: '600' }, suggestions: { marginTop: 6, borderWidth: 1, borderRadius: Radius.md, paddingVertical: Spacing.sm, overflow: 'hidden' }, suggestionRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center' }, suggestion: { minHeight: 56, flex: 1, paddingLeft: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, deletePreset: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }, suggestionIcon: { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, suggestionCopy: { flex: 1 }, suggestionTitle: { fontSize: 14, fontWeight: '700' }, suggestionCaption: { fontSize: 11, marginTop: 2 }, noSuggestions: { padding: Spacing.lg, textAlign: 'center' },
  notesInput: { minHeight: 88, borderWidth: 1, borderRadius: Radius.md, padding: Spacing.lg, textAlignVertical: 'top', fontSize: 15 }, savePreset: { alignSelf: 'flex-start', minHeight: 40, borderWidth: 1, borderRadius: Radius.full, paddingHorizontal: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }, savePresetText: { fontSize: 13, fontWeight: '800' }, field: { gap: Spacing.sm }, label: { fontSize: 14, fontWeight: '800' }, hint: { fontSize: 12, marginTop: -4 }, chips: { flexDirection: 'row', gap: Spacing.sm, flexWrap: 'wrap' }, chip: { minHeight: 40, paddingHorizontal: Spacing.md, borderRadius: Radius.full, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 7 }, chipDot: { width: 8, height: 8, borderRadius: 4 }, weekdays: { flexDirection: 'row', gap: Spacing.sm, justifyContent: 'space-between' }, weekday: { width: 40, height: 40, borderWidth: 1, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  subtaskInputRow: { flexDirection: 'row', gap: Spacing.sm }, subtaskInput: { flex: 1, height: 48, borderWidth: 1, borderRadius: Radius.sm, paddingHorizontal: Spacing.md }, addStep: { width: 48, height: 48, borderRadius: Radius.sm, alignItems: 'center', justifyContent: 'center' }, draftSubtask: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, paddingHorizontal: Spacing.sm }, draftSubtaskText: { flex: 1, fontSize: 14 },
  priorityRow: { flexDirection: 'row', gap: Spacing.md }, priority: { flex: 1, minHeight: 104, padding: Spacing.lg, borderRadius: Radius.md, borderWidth: 1, gap: 5 }, priorityTitle: { fontSize: 16, fontWeight: '700' }, caption: { fontSize: 12, lineHeight: 17 }, switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderRadius: Radius.md, padding: Spacing.lg }, switchLabel: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: Spacing.md }, switchTitle: { fontSize: 15, fontWeight: '700' }, deleteTask: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm }, deleteTaskText: { fontWeight: '800' }, save: { position: 'absolute', left: Spacing.xl, right: Spacing.xl, bottom: Spacing.xl, height: 56, borderRadius: Radius.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm }, saveText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
});
