import { Platform, StyleSheet } from 'react-native';

import { BottomTabInset, MaxContentWidth, Radius, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1 }, safe: { flex: 1 }, content: { width: '100%', maxWidth: MaxContentWidth, alignSelf: 'center', padding: Spacing.xl, paddingTop: Platform.OS === 'web' ? 108 : Spacing.xl, paddingBottom: BottomTabInset + 90, gap: Spacing.xl }, kicker: { fontSize: 12, fontWeight: '800', letterSpacing: 1.3 }, title: { fontSize: 31, fontWeight: '800' }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 4 }, overview: { minHeight: 150, borderRadius: Radius.lg, padding: Spacing.xl, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, overviewLabel: { color: '#FFFFFFCC', fontSize: 12, fontWeight: '800', letterSpacing: 1 }, overviewValue: { color: '#FFFFFF', fontSize: 36, fontWeight: '900', marginVertical: 4 }, overviewHint: { color: '#FFFFFFBB', fontSize: 12 }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.md }, summary: { minWidth: 140, flex: 1, minHeight: 84, borderWidth: 1, borderRadius: Radius.md, padding: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }, summaryDot: { width: 10, height: 10, borderRadius: 5 }, summaryValue: { fontSize: 17, fontWeight: '800' }, summaryLabel: { fontSize: 11, marginTop: 2 }, sectionTitle: { fontSize: 21, fontWeight: '800' }, sectionCaption: { fontSize: 12, marginTop: 3 }, people: { gap: Spacing.sm }, person: { minHeight: 78, borderWidth: 1, borderRadius: Radius.md, padding: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }, avatar: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, personCopy: { minWidth: 0, flex: 1 }, personName: { fontSize: 16, fontWeight: '800' }, personMeta: { fontSize: 11, marginTop: 4 }, personBalance: { alignItems: 'flex-end' }, personAmount: { fontSize: 14, fontWeight: '900' }, personPending: { fontSize: 10, marginTop: 2 }, empty: { minHeight: 260, borderWidth: 1, borderRadius: Radius.lg, alignItems: 'center', justifyContent: 'center', padding: Spacing.xl, gap: Spacing.sm }, emptyIcon: { width: 58, height: 58, borderRadius: 18, alignItems: 'center', justifyContent: 'center' }, emptyTitle: { fontSize: 19, fontWeight: '800' }, emptyText: { maxWidth: 430, textAlign: 'center', fontSize: 13, lineHeight: 20 }, emptyButton: { marginTop: Spacing.sm, borderRadius: Radius.full, paddingHorizontal: Spacing.xl, paddingVertical: 12 }, emptyButtonText: { color: '#FFFFFF', fontWeight: '800' },
  sections: { flexDirection: 'row', gap: Spacing.sm },
  sectionButton: { minHeight: 48, flex: 1, borderWidth: 1, borderRadius: Radius.full, paddingHorizontal: Spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm },
  personOpen: { minWidth: 0, flex: 1, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  personDelete: { width: 40, height: 48, alignItems: 'center', justifyContent: 'center' },
});
