import { Platform, StyleSheet } from 'react-native';

import { BottomTabInset, MaxContentWidth, Radius, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  safe: { flex: 1 },
  scroll: { width: "100%" },
  content: {
    width: "100%",
    maxWidth: MaxContentWidth,
    alignSelf: "center",
    padding: Spacing.xl,
    paddingTop: Platform.OS === "web" ? 108 : Spacing.xl,
    paddingBottom: BottomTabInset + 80,
    gap: Spacing.xl,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: Spacing.lg,
  },
  kicker: { fontSize: 12, fontWeight: "800", letterSpacing: 1.3 },
  title: { fontSize: 31, fontWeight: "800" },
  headerActions: { flexDirection: "row", gap: Spacing.sm },
  actionButton: {
    height: 42,
    borderRadius: Radius.full,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
  },
  actionText: { fontSize: 13, fontWeight: "700" },
  search: {
    height: 52,
    borderRadius: Radius.md,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
    paddingHorizontal: Spacing.lg,
  },
  searchInput: { flex: 1, fontSize: 16 },
  filterSection: { gap: Spacing.sm },
  filterLabel: { fontSize: 11, fontWeight: "800", letterSpacing: 1.1 },
  filterScroll: { flexGrow: 0, height: 42 },
  filters: { gap: Spacing.sm, alignItems: "center" },
  filter: {
    height: 40,
    borderRadius: Radius.full,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.md,
    gap: 7,
  },
  filterGroup: {
    height: 40,
    borderRadius: Radius.full,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
  filterMain: {
    height: 40,
    paddingLeft: Spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  folderChip: {
    height: 40,
    borderRadius: Radius.full,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    overflow: "hidden",
  },
  folderMain: {
    paddingLeft: Spacing.md,
    paddingRight: Spacing.sm,
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  deleteIcon: {
    width: 36,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  dot: { width: 8, height: 8, borderRadius: 4 },
  filterText: { fontWeight: "700" },
  count: { fontSize: 12, marginLeft: Spacing.xs, marginRight: 2 },
  summaryText: { fontSize: 13, fontWeight: "600" },
  list: { gap: Spacing.sm },
  empty: {
    minHeight: 100,
    borderWidth: 1,
    borderRadius: Radius.md,
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.sm,
  },
  backdrop: {
    flex: 1,
    backgroundColor: "#00000077",
    alignItems: "center",
    justifyContent: "center",
    padding: Spacing.xl,
  },
  dialog: {
    width: "100%",
    maxWidth: 440,
    borderRadius: Radius.lg,
    padding: Spacing.xl,
    gap: Spacing.xl,
  },
  dialogHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  dialogIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  dialogTitle: { fontSize: 21, fontWeight: "800", textTransform: "capitalize" },
  dialogSubtitle: { fontSize: 12, marginTop: 3 },
  dialogInput: {
    height: 52,
    borderWidth: 1,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.lg,
    fontSize: 16,
  },
  dialogActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: Spacing.xl,
  },
  dialogSave: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: 11,
    borderRadius: Radius.full,
  },
  dialogSaveText: { color: "#FFFFFF", fontWeight: "800" },
  deleteMessage: { lineHeight: 20, marginTop: Spacing.sm },
  choiceButton: {
    minHeight: 66,
    borderWidth: 1,
    borderRadius: Radius.md,
    padding: Spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.md,
  },
  choiceTitle: { fontSize: 14, fontWeight: "800" },
  cancelButton: { alignSelf: "center", padding: Spacing.sm },
});
