import { Platform, StyleSheet } from 'react-native';

import { BottomTabInset, MaxContentWidth, Radius, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  screen: { flex: 1 },
  safe: { flex: 1 },
  scroll: { width: "100%" },
  content: {
    width: "100%",
    maxWidth: MaxContentWidth,
    alignSelf: "center",
    padding: Spacing.xl,
    paddingTop: Platform.OS === "web" ? 108 : Spacing.xl,
    paddingBottom: BottomTabInset + 80,
    gap: Spacing.xxl,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerCopy: { flex: 1, minWidth: 0 },
  kicker: { fontSize: 12, fontWeight: "800", letterSpacing: 1.4 },
  title: { fontSize: 31, lineHeight: 39, fontWeight: "800" },
  date: { fontSize: 14 },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  stats: { flexDirection: "row", gap: Spacing.sm },
  stat: { flex: 1, minWidth: 0, borderWidth: 1, borderRadius: Radius.md, padding: Spacing.md, gap: 3 },
  statValue: { fontSize: 21, fontWeight: "900" },
  statLabel: { fontSize: 11, fontWeight: "700" },
  progressCard: {
    minHeight: 164,
    borderRadius: Radius.lg,
    padding: Spacing.xl,
    flexDirection: "row",
    gap: Spacing.xl,
    justifyContent: "space-between",
    alignItems: "center",
    overflow: "hidden",
  },
  progressCopy: { flex: 1, minWidth: 0 },
  progressEyebrow: {
    color: "#EADDFF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  progressTitle: {
    color: "#FFFFFF",
    fontSize: 24,
    lineHeight: 31,
    fontWeight: "800",
    marginTop: 9,
    marginRight: 10,
  },
  progressCaption: {
    color: "#EADDFF",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 5,
  },
  progressRing: {
    flexShrink: 0,
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 8,
    borderColor: "#CDB7FF",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  progressNumber: { color: "#FFFFFF", fontSize: 21, fontWeight: "900" },
  percent: { color: "#FFFFFF", fontSize: 11, marginLeft: 2 },
  section: { gap: Spacing.md },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { fontSize: 20, fontWeight: "800" },
  alarmPill: {
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Radius.full,
  },
  alarmText: { fontSize: 11, fontWeight: "800" },
  list: { gap: Spacing.sm },
  empty: {
    minHeight: 76,
    borderWidth: 1,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.lg,
    flexDirection: "row",
    gap: Spacing.md,
    alignItems: "center",
  },
  emptyIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: { flex: 1, fontSize: 14 },
  profileBackdrop: { flex: 1, backgroundColor: '#00000077', alignItems: 'center', justifyContent: 'center', padding: Spacing.xl },
  profileDialog: { width: '100%', maxWidth: 420, maxHeight: '90%', borderRadius: Radius.lg },
  profileDialogContent: { padding: Spacing.xl, gap: Spacing.lg },
  profileIcon: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  profileTitle: { fontSize: 22, fontWeight: '800' },
  profileText: { fontSize: 14, lineHeight: 20, marginTop: 4 },
  profileInput: { height: 52, borderWidth: 1, borderRadius: Radius.sm, paddingHorizontal: Spacing.lg, fontSize: 16 },
  profileRestore: { minHeight: 68, borderWidth: 1, borderRadius: Radius.md, padding: Spacing.md, flexDirection: 'row', alignItems: 'center', gap: Spacing.md },
  profileDemoCopy: { minWidth: 0, flex: 1 },
  profileDemoTitle: { fontSize: 14, fontWeight: '800' },
  profileDemoText: { fontSize: 11, lineHeight: 16, marginTop: 2 },
  profileActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: Spacing.xl },
  profileSave: { borderRadius: Radius.full, paddingHorizontal: Spacing.xl, paddingVertical: 11 },
  profileSaveText: { color: '#FFFFFF', fontWeight: '800' },
});
